const players = [
    {
        id: 1,
        name: "Virat Kohli",
        role: "All-Rounder",
        country: "India",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "Right-Arm Off Spin",
        price: 1500000,
        image: "https://images2.minutemediacdn.com/image/upload/c_crop,w_692,h_389,x_0,y_0/c_fill,w_1080,ar_16:9,f_auto,q_auto,g_auto/images%2FvoltaxMediaLibrary%2Fmmsport%2Fcricket_on_si%2F01j7s44j46nrsd3b2qcy.jpg",
    },
    {
        id: 3,
        name: "Steve Smith",
        role: "Batsman",
        country: "Australia",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "Right-Arm Leg Spin",
        price: 1800000,
        image: "https://api.bdcrictime.com/steve-smith-07_03_2022.jpg",
    },
    {
        id: 4,
        name: "Ben Stokes",
        role: "All-Rounder",
        country: "England",
        battingStyle: "Left-Hand Bat",
        bowlingStyle: "Right-Arm Fast-Medium",
        price: 2200000,        
        image: "https://static.toiimg.com/thumb/msid-111623863,imgsize-27652,width-400,resizemode-4/111623863.jpg",
    },
    {
        id: 5,
        name: "Rohit Sharma",
        role: "Batsman",
        country: "India",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "Right-Arm Off Spin",
        price: 1400000,
        image: "https://static.toiimg.com/thumb/msid-113209976,imgsize-37996,width-400,resizemode-4/113209976.jpg",
    },
    {
        id: 6,
        name: "Kane Williamson",
        role: "Batsman",
        country: "New Zealand",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "Right-Arm Off Spin",
        price: 1300000,
        image: "https://www.bssnews.net/assets/news_photos/2024/06/19/image-195677-1718784020.jpg",    
    },
    {
        id: 7,
        name: "David Warner",
        role: "Batsman",
        country: "Australia",
        battingStyle: "Left-Hand Bat",
        bowlingStyle: "Right-Arm Leg Spin",
        price: 1600000,
        image: "https://yespunjab.com/wp-content/uploads/2024/07/David-Warner-aus.jpg",
    },
    {
        id: 8,
        name: "Babar Azam",
        role: "Batsman",
        country: "Pakistan",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "Right-Arm Off Spin",
        price: 1700000,
        image: "https://i.aaj.tv/primary/2023/05/03125200e8011d7.webp",
    },
    {
        id: 9,
        name: "Andre Russell",
        role: "All-Rounder",
        country: "West Indies",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "Right-Arm Fast",
        price: 2100000,
        image: "https://images.firstpost.com/uploads/2024/03/AI_9523-1-2024-03-6d143efd5ad7eb67a655864855257705-1200x675.jpg?im=FitAndFill=(596,336)",
    },
    {
        id: 10,
        name: "Jos Buttler",
        role: "Wicketkeeper-Batsman",
        country: "England",
        battingStyle: "Right-Hand Bat",
        bowlingStyle: "N/A",
        price: 1900000,
        image: "https://e0.365dm.com/23/10/1600x900/skysports-cricket-cricket-world-cup_6309036.jpg?20231004175525",
    }
];

export default players;